
// Start of #include "/lib/MenuInitializer.glsl"


/* Force Optifine to recognize options
#ifdef EXPOSURE
#ifdef SUN_LIGHT_LEVEL
#ifdef SKY_LIGHT_LEVEL
#ifdef AMBIENT_LIGHT_LEVEL
#ifdef TORCH_LIGHT_LEVEL
#ifdef SKY_BRIGHTNESS


#ifdef BLOOM_AMOUNT
#ifdef BLOOM_CURVE

#ifdef MOTION_BLUR
#ifdef VARIABLE_MOTION_BLUR_SAMPLES
#ifdef MAX_MOTION_BLUR_SAMPLE_COUNT
#ifdef VARIABLE_MOTION_BLUR_SAMPLE_COEFFICIENT
#ifdef CONSTANT_MOTION_BLUR_SAMPLE_COUNT
#ifdef MOTION_BLUR_INTENSITY
#ifdef MAX_MOTION_BLUR_AMOUNT

#ifdef WAVING_GRASS
#ifdef WAVING_LEAVES
#ifdef WAVING_WATER

#ifdef SHADOW_MAP_BIAS
#ifdef EXTENDED_SHADOW_DISTANCE
#ifdef SHADOW_TYPE
#ifdef PLAYER_SHADOW

#ifdef FOG_ENABLED
#ifdef FOG_POWER
#ifdef VOLUMETRIC_FOG_POWER
#ifdef ATMOSPHERIC_SCATTERING_AMOUNT

#ifdef POISSON_GI
#ifdef GI_TRANSLUCENCE
#ifdef GI_RADIUS
#ifdef GI_QUALITY
#ifdef GI_BOOST


#ifdef COMPOSITE0_SCALE


#ifdef REFLECTION_EDGE_FALLOFF

#ifdef RECALCULATE_DISPLACED_NORMALS

#ifdef FORWARD_SHADING


#ifdef DEBUG

#ifdef STAGE_VIEW
#ifdef DEBUG_MULTIPLYER
#ifdef DEBUG_CURVE
*/


// End of #include "/lib/MenuInitializer.glsl"
